// website/src/routes/recept/[id]/+page.svelte
<script lang="ts">
    import { page } from '$app/stores';
    import type { Recipe } from "src/models/Recipe";
    import { Api } from 'src/models/api/Api';
    import { onMount } from 'svelte';
    import { goto } from '$app/navigation';
    import { fade } from "svelte/transition";
    // Icons
    import NoteIcon from 'src/icons/message.svelte';
    import Delete from 'src/icons/delete.svelte';
    import ExternalLink from 'src/icons/external-link.svelte';
    import Edit from 'src/icons/edit.svelte';
    import Header from 'src/components/Header.svelte';

    let error = false;
    let recipe: Recipe | null;
    let domain: string;

    onMount(async () => {
        const id = Number($page.params.id);
        recipe = await Api.recipes.getById(id);
        if(recipe == null) 
            error = true;
        else {
            const url = new URL(recipe.url);
            domain = url.hostname;
        }
    })

    async function clickDelete(){
        if(recipe?.id == null) return;
        const confirmDelete = confirm("Vill du ta bort det här receptet?");
        if(confirmDelete){
            await Api.recipes.delete(recipe.id);
            goto("/");
        }
    }
</script>



{#if recipe}
<Header backUrl="/" >
    <a href={recipe.url} class="open-recipe icon-button button-primary">
        <span class="text">Öppna recept</span>
        <span class="icon"><ExternalLink /></span>
        <!-- position: absolute -->
        <span class="domain">{domain}</span>
    </a>
</Header>
<article in:fade>    
    <h2>{recipe.linkPreview?.title}</h2>
    {#if recipe.notes}
        <div class="notes">
            <span class="icon"><NoteIcon /></span>            
            <p>{recipe.notes}</p>
        </div>        
    {/if}
    <img src={recipe.linkPreview?.imageUrl} alt="" />
    <p class="description">{recipe.linkPreview?.description}</p>
    <div class="buttons">
        <!-- REDIGERA SIDAN EJ KLAR -->
        <a href="#" class="icon-button button-secondary">
            <span class="text">Redigera</span>
            <span class="icon"><Edit /></span>
        </a>
        <button on:click={clickDelete} class="icon-button button-secondary">
            <span class="text">Ta bort</span>
            <span class="icon"><Delete /></span>
        </button>
    </div>
</article>
{/if}

{#if error}
    <Header backUrl="/" />
    <p>Hittar inte receptet du försöker nå</p>
{/if}

<style>
    .open-recipe{
        position: relative;        
    }
    .icon-button{
        display: flex;
        align-items: center;
        gap: 10px;
        padding-right: 14px;
    }
    .icon{
        display: inline-block;
        height: 1.5rem;
        /* 
            Måste vara min-width.
            Med vanlig width kan storleken bli mindre när knappen trycks ihop
        */
        min-width: 1.5rem;
        stroke: currentColor;
        stroke-width: 2;
    }
    .domain{
        position: absolute;
        bottom: -1.3rem;
        left: 0; right: 0;
        color: gray;
        font-size: 0.7rem;
        text-align: center;
    }

    h2{
        text-align: center;
        font-weight: 500;
    }
    .notes{
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 6px;
        margin-top: 10px;
        color: var(--black);
    }
    img{
        width: 100%;
        max-height: 50vh;
        margin: 20px auto;
        object-fit: cover;
        border-radius: 10px;
    }
    .description{
        max-width: 40rem;
        margin: auto;
    }

    .buttons{
        display: flex;
        justify-content: space-evenly;
        gap: 10px;
        margin-block: 100px;
    }
    
</style>

// website_react/src/routes/recept/[id].tsx
import { useLocation, useNavigate } from "react-router-dom"
import Header from "../../components/Header";
import { ReactComponent as ExternalLink} from "../../icons/external-link.svg";
import { ReactComponent as NoteIcon} from "../../icons/message.svg";
import { ReactComponent as Edit} from "../../icons/edit.svg";
import { ReactComponent as Delete} from "../../icons/delete.svg";
import { Api } from "../../models/api/Api";
import "./recept.css"

export default function Id(){    
    const navigate = useNavigate();
    const recipe = useLocation().state;
    const domain = new URL(recipe.url).hostname; 
    // TODO: hämta recept om det inte skickas som state med <Link>
    //const { id } = useParams();

    async function clickDelete(){
        if(recipe?.id == null) return;
        const confirmDelete = window.confirm("Vill du ta bort det här receptet?");
        if(confirmDelete){
            await Api.recipes.delete(recipe.id);
            navigate("/");
        }
    }

    return(
        <>
        <Header>
            <a href={recipe.url} className="open-recipe icon-button button-primary">
                <span className="text">Öppna recept</span>
                <span className="icon"><ExternalLink /></span>
                {/* position: absolute */}
                <span className="domain">{domain}</span>
            </a>
        </Header>
        <article id="recipe">    
            <h2>{recipe.linkPreview?.title}</h2>
            {recipe.notes && (
                <div className="notes">
                    <span className="icon"><NoteIcon /></span>            
                    <p>{recipe.notes}</p>
                </div>
            )}
            <img src={recipe.linkPreview?.imageUrl} alt="" />
            <p className="description">{recipe.linkPreview?.description}</p>
            <div className="buttons">
                {/* REDIGERA SIDAN EJ KLAR */}
                <a href="#top" className="icon-button button-secondary">
                    <span className="text">Redigera</span>
                    <span className="icon"><Edit /></span>
                </a>
                <button onClick={clickDelete} className="icon-button button-secondary">
                    <span className="text">Ta bort</span>
                    <span className="icon"><Delete /></span>
                </button>
            </div>
        </article>
        </>
    )
}
